KBT: 0.00411
proteins:
  - tag: 0 # Type 0, Sticky model
    walkOff: false
    PtoAPratio: 1.
    fixedEnd0: true
    #properties:
    freeLength: 0.03 # um
    rc: 0.039 # um, (D/2 + \ell_0)/2
    kappa: 50.0 # pN/um
    fstall: 5.0 # pN
    lambda: 0.0 # dimensionless
    diffUnbound: 0.01 # um^2/s
    #  diffUnbound: ChiParam(format_str = "diffU{:.2g}", paramtype=float, values=[.005, .01, .05, .1, .5, 1., 5.0, 10.])
    vmax: [0.0, 0.0] # um/s, positive towards plus end
    vdrag: [false, false] # um/s, (N/A)
    diffBoundS: [0., 0.] # um^2/s
    diffBoundD: [0., 0.] # um^2/s
    # KMC parameters
    useBindVol: true
    eps: 1. # binding site per segment
    Ka: [3.22, 3.22] # (uM/L)^{-1}, used in U<->S
    ko_s: [0., 0.] # 1/s, off-rate
    Ke: 
      - 0.0 # dimensionless, used in S<->D
      - 30
    ko_d: # 1/s, off-rate
      - 0 
      - 30
    # numbers:
    freeNumber: 0 
    fixedLocationPerMT: [0] # given in [-1,1]. otherwise random

