KBT: -0.00411
conMaxIte: 1000000
conResTol: 1e-5
conSolverChoice: 0
dt: 0.0001
initBoxHigh:
- 2.5
- 2.5
- 2.5
initBoxLow:
- -2.5
- -2.5
- -2.5
initCircularX: true
initOrient:
- 2
- 0
- 0
linkGap: 0.0002
linkKappa: 3650
logLevel: 3
monolayer: false
rngSeed: 1234
simBoxHigh:
- 5.0
- 5.0
- 5.0
simBoxLow:
- -5.0
- -5.0
- -5.0
simBoxPBC:
- false
- false
- false
sylinderColBuf: 0.02
sylinderDiameter: 0.02
sylinderDiameterColRatio: 1.0
sylinderFixed: false
sylinderLength: 0.0
sylinderLengthColRatio: 1.0
sylinderLengthSigma: 0
sylinderNumber: 1000
timeSnap: 0.05
timeTotal: 0.005
timerLevel: 3
viscosity: 1
