KBT: 0.00411
proteins:
  - tag: 0 # Type 0, Symmetric, Blackwell 2015
    walkOff: true
    PtoAPratio: 1.
    fixedEnd0: false
    #properties:
    freeLength: 0.025 # um
    rc: 0.025 # um, (D/2 + \ell_0)/2
    kappa: 200.0 # pN/um
    fstall: 5.0 # pN
    lambda: 0.5 # dimensionless
    diffUnbound: 1.0 # um^2/s
    vmax: [0.5, 0.5] # um/s, positive towards plus end
    diffBoundS: [0, 0] # um^2/s
    diffBoundD: [0, 0] # um^2/s
    # KMC parameters
    useBindVol: false
    eps: 400 # um^{-1} 13 protofilaments at 8nm per block
    Ka: [100, 100] # (uM/L)^{-1}, used in U<->S
    ko_s: [28.1, 28.1] # 1/s, off-rate
    Ke: [100, 100] # dimensionless, used in S<->D
    ko_d: [28.1, 28.1] # 1/s, off-rate
    # numbers:
    freeNumber: 20000
    fixedLocationPerMT: [] # given in [-1,1]. otherwise random
