# program settings
rngSeed: 1234
timerLevel: 3
logLevel: 3
# simulation box
simBoxLow: [-0.35, -0.35, -0.35]
simBoxHigh: [0.35, 0.35, 0.35]
simBoxPBC: [true, true, true]
monolayer: false
# initialization box
initBoxLow: [-0.35, -0.35, -0.35]
initBoxHigh: [0.35, 0.35, 0.35]
# initialization inside a circle along X direction
initCircularX: false
initPreSteps: 0
# components < -1  or > 1 will be randomly set
initOrient: [0, 0, 2]
# physical settings
viscosity: 0.01 #pN/(um^2.s)
KBT: -0.00411 #pN.um, < 0 no brownian dynamics
linkKappa: 1000.0
# sylinder
sylinderFixed: false
sylinderNumber: 500
sylinderLength: 0.25 # um
sylinderLengthSigma: 0 # logNormal distribution
sylinderDiameter: 0.025 # um
sylinderColBuf: .025 # um
sylinderDiameterColRatio: 1.0
sylinderLengthColRatio: 1.0
# timestepping
dt: 0.0001 # s
timeTotal: 10. # s
timeSnap: 0.01 # s
# LCP Solver
conResTol: 1e-5
conMaxIte: 100000
conSolverChoice: 0
# confinement
boundaries:
