# program settings
rngSeed: 1234
# simulation box
simBoxLow: [0.0, 0.0, 0.0]
simBoxHigh: [10.0, 10.0, 10.0]
simBoxPBC: [true, true, true]
monolayer: false
# initialization box
initBoxLow: [0.0, 0.0, 0.0]
initBoxHigh: [10.0, 10.0, 10.0]
# initialization inside a circle along X direction
initCircularX: false
# components < -1  or > 1 will be randomly set
initOrient: [2, 2, 2]
# physical settings
viscosity: 0.01 #pN/(um^2.s)
KBT: -0.00411 #pN.um, 300K
linkKappa: 1000.0
# sylinder
sylinderFixed: false
sylinderNumber: 40000
sylinderLength: 0.5 # um
sylinderLengthSigma: 0 # logNormal distribution
sylinderDiameter: 0.025 # um
sylinderColBuf: 1.0 #
sylinderDiameterColRatio: 1.0
sylinderLengthColRatio: 1.0
# timestepping
dt: 0.0001 # s
timeTotal: 500.0 # s
timeSnap: 0.01 # s
# LCP Solver
conResTol: 1e-5
conMaxIte: 1000000
conSolverChoice: 0
