# program settings
rngSeed: 1234
logLevel: 2
# simulation box
simBoxLow: [0.0, 0.0, 0.0]
simBoxHigh: [3.0, 1.0, 1.0]
simBoxPBC: [true, false, false]
monolayer: false
# initialization box
initBoxLow: [0.0, 0.0, 0.0]
initBoxHigh: [3.0, 1.0, 1.0]
# components < -1  or > 1 will be randomly set
initOrient: [2, 0, 0]
# physical settings
viscosity: 1.0 #pN/(um^2.s)
KBT: -0.00411 #pN.um, 300K
linkKappa: 1000.0
# sylinder
sylinderFixed: false
sylinderNumber: 3000
sylinderLength: 0.5 # um
sylinderLengthSigma: 0 # logNormal distribution
sylinderDiameter: 0.025 # um
sylinderColBuf: 1.0 #
sylinderDiameterColRatio: 1.0
sylinderLengthColRatio: 1.0
# timestepping
dt: 0.0001 # s
timeTotal: 30.0 # s
timeSnap: 0.01 # s
# LCP Solver
conResTol: 1e-5
conMaxIte: 1000000
conSolverChoice: 0
boundaries:
  - type: "tube"
    center: [1, 0.5, 0.5]
    radius: 0.5
    axis: [1, 0, 0]
    inside: true


